language: go

go:
  - 1.11.x

os:
  - linux

before_script:
  - lsb_release -a
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get install -y telnet
  - go get
  - go build
  - cd testserver
  - sleep 3
  - ./ibgwstart
  - sleep 15
  - cd ..
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=c.out ./...
  - $GOPATH/bin/goveralls -coverprofile=c.out -service=travis-ci

after_script:
  - ./testserver/ibgwstop
